objects/Colleages__c.object
<CustomObject>
    <label>Colleages</label>
    <nameField>
        <label>Colleage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Colleage_Phone_Number__c</fullName>
        <description>This field is created to store colleage Phone</description>
        <inlineHelpText>Phone number can start with any number not text</inlineHelpText>
        <label>Colleage Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Colleage_Registration_Fee__c</fullName>
        <label>Colleage Registration Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/ColleageController.cls
public class ColleageController {
    @Auraenabled(cacheable=true)
    public static  list<Colleages__c>getcolleages(){
        list<Colleages__c> ColleagesList = [Select Id,
                                                Name,
                                                Colleage_Phone_Number__c,
                                                Colleage_Registration_Fee__c
                                           FROM Colleages__c];
                                return ColleagesList;
    }

}